version: '3.3'
services:
  app:
    container_name: ${APP_CONTAINER_NAME}
    build: .
    networks: 
      - frontend
      - backend
    ports:
      - "8080:8080"
  redis:
    container_name: ${DB_REDIS_CONTAINER_NAME}
    networks: 
      - frontend
    image: redis:alpine  
    command: redis-server --requirepass ${DB_REDIS_PASS}
    restart: always
    ports: 
      - ${DB_REDIS_PORT}:6379
  mongodb:
    container_name: ${DB_MONGO_CONTAINER_NAME}
    networks: 
      - frontend
    image: mongo:latest
    restart: always
    ports:
      - ${DB_MONGO_PORT}:27017  
    environment:
      TZ: ${TIMEZONE}
      MONGO_INITDB_DATABASE: ${DB_MONGO_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${DB_MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_MONGO_PASS}
  mysql:
    container_name: ${DB_MYSQL_CONTAINER_NAME}
    networks: 
      - backend
    image: mysql:5.7
    restart: always
    ports:
      - ${DB_MYSQL_PORT}:3306    
    environment:
      TZ: ${TIMEZONE}
      MYSQL_DATABASE: ${DB_MYSQL_NAME}
      MYSQL_USER: ${DB_MYSQL_USERNAME}
      MYSQL_PASSWORD: ${DB_MYSQL_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_MYSQL_ROOT_PASS}
networks: 
  frontend:
    name: frontend
  backend:
    name: backend